# Generated by Django 2.0.8 on 2018-08-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='URLTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ViewTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_temp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('view_temp_code', models.TextField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
