# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModelField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=30)),
                ('fieldType', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicationManager.AppModel'),
        ),
    ]
