# Generated by Django 2.2.4 on 2019-09-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayout',
            name='layout_description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='applicationcomponenttemplate',
            name='temp_type',
            field=models.CharField(choices=[('generic', 'Generic Purpose Template'), ('view', 'View Template'), ('url', 'URL Template'), ('html', 'HTML file Template'), ('license', 'License File Template'), ('python', 'Python File Template')], default='generic', max_length=60),
        ),
    ]
