# Generated by Django 3.0.2 on 2020-03-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
