# Generated by Django 2.0.7 on 2018-07-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsettings',
            name='defaultSettings',
        ),
        migrations.RemoveField(
            model_name='applicationsettings',
            name='user',
        ),
    ]
