# Generated by Django 2.0.8 on 2018-08-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0002_templatetemplate_urltemplate_viewtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationComponentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('temp_type', models.CharField(choices=[('generic', 'Generic Template'), ('view', 'View Template'), ('url', 'URL Template'), ('html', 'Django Template Template')], default='generic', max_length=60)),
                ('temp_code', models.TextField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TemplateTemplate',
        ),
        migrations.DeleteModel(
            name='URLTemplate',
        ),
        migrations.DeleteModel(
            name='ViewTemplate',
        ),
    ]
