# Generated by Django 3.0.4 on 2020-03-30 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0002_application_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='db_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='default',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='field',
            name='null',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='rel',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='serialize',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='field',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(default='A brief explanation of this application.', max_length=500),
        ),
    ]
