# Generated by Django 3.0.4 on 2020-07-22 11:26

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0002_auto_20200716_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoproject',
            name='pids',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
