# Generated by Django 2.2.4 on 2019-09-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0003_auto_20190907_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelayout',
            name='layout_description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
