# Generated by Django 3.0.4 on 2020-03-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0003_auto_20200330_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='max_length',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='field',
            name='primary_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='verbose_name',
            field=models.CharField(default='vname', max_length=40),
        ),
        migrations.AlterField(
            model_name='field',
            name='rel',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
