# Generated by Django 3.0.8 on 2020-08-30 14:12

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0003_auto_20200722_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoproject',
            name='pids',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='status',
            field=models.CharField(choices=[('Initializing', 'Initializing'), ('Pending', 'Pending'), ('Stopped', 'Stopped'), ('Running', 'Running')], default='Initializing', max_length=15),
        ),
    ]
