# Generated by Django 2.0.8 on 2018-08-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0003_auto_20180830_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcomponenttemplate',
            name='definition',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationcomponenttemplate',
            name='temp_type',
            field=models.CharField(choices=[('generic', 'Generic Template'), ('view', 'View Template'), ('url', 'URL Template'), ('html', 'Django Template Template'), ('file', 'File Template')], default='generic', max_length=60),
        ),
    ]
