# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0003_auto_20161229_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='model',
        ),
        migrations.AddField(
            model_name='modelfield',
            name='fieldTypeParameters',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelfield',
            name='fieldType',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=30),
        ),
        migrations.DeleteModel(
            name='AppModel',
        ),
        migrations.AddField(
            model_name='model',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicationManager.Application'),
        ),
        migrations.AddField(
            model_name='modelfield',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applicationManager.Model'),
            preserve_default=False,
        ),
    ]
