# Generated by Django 3.0.4 on 2020-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0004_auto_20200330_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoproject',
            name='pid',
            field=models.IntegerField(default='-999', null=True),
        ),
    ]
