# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0004_auto_20170501_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelfield',
            old_name='fieldName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='modelfield',
            old_name='fieldType',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='modelfield',
            old_name='fieldTypeParameters',
            new_name='type_parameter',
        ),
    ]
