# Generated by Django 2.2.4 on 2019-09-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0004_auto_20190907_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayout',
            name='layout_icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
