# Generated by Django 2.0.7 on 2018-07-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0004_auto_20180728_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
