# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0005_auto_20170504_0115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelField',
            new_name='Field',
        ),
    ]
