# Generated by Django 3.0.4 on 2020-03-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0005_auto_20200330_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoproject',
            name='enable_drf_api',
            field=models.BooleanField(default=True, verbose_name='Enable DRF for Application'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='enable_messages',
            field=models.BooleanField(default=True, verbose_name='Enable Messages Framework for Application'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='sample_app',
            field=models.BooleanField(default=True, verbose_name='Create Sample Application'),
        ),
    ]
