# Generated by Django 2.0.7 on 2018-07-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0005_auto_20180728_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpage',
            name='page_type',
            field=models.CharField(choices=[('predefined', 'Predefined Template'), ('empty', 'Empty Page'), ('landing', 'Landing Page'), ('index', 'Application Index Page'), ('about', 'About Page'), ('contact', 'Contact Page')], default='predefined', max_length=25),
        ),
        migrations.AlterField(
            model_name='applicationpage',
            name='page_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicationManager.PageLayout'),
        ),
    ]
