# Generated by Django 2.0.8 on 2018-08-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0005_auto_20180830_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcomponenttemplate',
            name='temp_engine',
            field=models.CharField(choices=[('django', 'Django Template'), ('jinja2', 'Jinja2 Template'), ('mako', 'Mako Template'), ('mustache', 'Mustache Template')], default='django', max_length=60),
        ),
    ]
