# Generated by Django 2.0.8 on 2018-08-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0006_applicationcomponenttemplate_temp_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_list', to='applicationManager.Application'),
        ),
    ]
