# Generated by Django 3.0.4 on 2020-03-30 20:14

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0006_auto_20200330_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoproject',
            name='pid',
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='pids',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
