# Generated by Django 2.0.8 on 2018-08-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0006_auto_20180730_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('url_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationViewMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(blank=True, max_length=50, null=True)),
                ('view_code', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views62', to='applicationManager.Application')),
            ],
        ),
        migrations.AddField(
            model_name='applicationurl',
            name='view_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_view', to='applicationManager.ApplicationViewMethod'),
        ),
    ]
