# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0006_auto_20170504_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('AutoField', 'AutoField'), ('BLANK_CHOICE_DASH', 'BLANK_CHOICE_DASH'), ('BigAutoField', 'BigAutoField'), ('BigIntegerField', 'BigIntegerField'), ('BinaryField', 'BinaryField'), ('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('CommaSeparatedIntegerField', 'CommaSeparatedIntegerField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('DecimalField', 'DecimalField'), ('DurationField', 'DurationField'), ('EmailField', 'EmailField'), ('Empty', 'Empty'), ('Field', 'Field'), ('FieldDoesNotExist', 'FieldDoesNotExist'), ('FilePathField', 'FilePathField'), ('FloatField', 'FloatField'), ('GenericIPAddressField', 'GenericIPAddressField'), ('IPAddressField', 'IPAddressField'), ('IntegerField', 'IntegerField'), ('NOT_PROVIDED', 'NOT_PROVIDED'), ('NullBooleanField', 'NullBooleanField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('PositiveSmallIntegerField', 'PositiveSmallIntegerField'), ('SlugField', 'SlugField'), ('SmallIntegerField', 'SmallIntegerField'), ('TextField', 'TextField'), ('TimeField', 'TimeField'), ('URLField', 'URLField'), ('UUIDField', 'UUIDField')], max_length=30),
        ),
        migrations.AlterField(
            model_name='field',
            name='type_parameter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
