# Generated by Django 2.0.8 on 2018-08-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0007_auto_20180830_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcomponenttemplate',
            name='definition',
            field=models.TextField(blank=True, default=None, max_length=200),
        ),
    ]
