# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0007_auto_20170504_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type_parameter',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
