# Generated by Django 2.0.8 on 2018-08-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0007_auto_20180824_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('type', models.CharField(default=None, max_length=30)),
                ('state', models.CharField(default=None, max_length=30)),
                ('definition', models.CharField(default=None, max_length=30)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicationManager.Application')),
            ],
        ),
    ]
