# Generated by Django 2.2.4 on 2019-09-07 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0007_auto_20190907_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('port', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1000)])),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
    ]
