# Generated by Django 2.2.4 on 2019-09-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0008_djangoproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoproject',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
