# Generated by Django 2.0.8 on 2018-08-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0008_applicationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsetting',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicationManager.Application'),
        ),
    ]
