# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0008_auto_20170504_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='modelName',
            new_name='name',
        ),
    ]
