# Generated by Django 2.0.8 on 2018-08-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0009_auto_20180826_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationSetting',
            new_name='Setting',
        ),
    ]
