# Generated by Django 2.2.4 on 2019-09-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0009_djangoproject_pid'),
        ('applicationManager', '0002_applicationlayout_description'),
    ]

    operations = [
    ]
