# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0010_auto_20170508_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type_parameter',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
