# Generated by Django 2.0.8 on 2018-08-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0010_auto_20180827_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='app',
        ),
    ]
