# Generated by Django 2.0.8 on 2018-08-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0011_remove_setting_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='state',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='type',
        ),
        migrations.AddField(
            model_name='setting',
            name='value',
            field=models.BooleanField(default=False, max_length=30),
        ),
    ]
