# Generated by Django 2.0.8 on 2018-08-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0012_auto_20180827_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applicationManager.Application')),
                ('setting', models.ManyToManyField(to='applicationManager.Setting')),
            ],
        ),
    ]
