# Generated by Django 2.0.8 on 2018-08-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0013_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettingsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicationManager.Application')),
            ],
        ),
        migrations.CreateModel(
            name='SettingDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('definition', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='app',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='setting',
        ),
        migrations.DeleteModel(
            name='AppSettings',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.AddField(
            model_name='appsettingslist',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicationManager.SettingDefinition'),
        ),
        migrations.AlterUniqueTogether(
            name='appsettingslist',
            unique_together={('app', 'setting')},
        ),
    ]
