# Generated by Django 2.0.8 on 2018-08-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0014_auto_20180827_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='api_enabled',
            field=models.BooleanField(default=False, help_text='If checked, enables the DRF API for the app'),
        ),
    ]
