# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0014_application_coming_soon_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
