# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0015_application_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
