# Generated by Django 2.0.8 on 2018-08-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0015_auto_20180827_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingdefinition',
            name='verbose_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='display_app_admin_menu',
            field=models.BooleanField(default=False, help_text='If checked, enables app specific admin menu on each page of the application'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='display_wbdap_admin_menu',
            field=models.BooleanField(default=False, help_text='If checked, enables the global WBDAP admin menu on each page of the application'),
        ),
    ]
