# Generated by Django 2.0.8 on 2018-08-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0016_auto_20180827_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppSettingsList',
            new_name='ApplicationSettingsList',
        ),
        migrations.RemoveField(
            model_name='applicationsettings',
            name='app',
        ),
        migrations.AlterField(
            model_name='settingdefinition',
            name='definition',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='ApplicationSettings',
        ),
    ]
