# Generated by Django 2.0.8 on 2018-08-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0017_auto_20180827_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettingslist',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_list', to='applicationManager.Application'),
        ),
    ]
