# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0017_auto_20170716_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='uuid',
        ),
    ]
