# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0018_remove_application_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
