# Generated by Django 2.0 on 2017-12-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0019_application_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='readmeContent',
            new_name='description',
        ),
    ]
