# Generated by Django 2.0 on 2017-12-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0020_auto_20171230_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='native',
            new_name='core_app',
        ),
    ]
