# Generated by Django 2.0 on 2017-12-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0021_auto_20171231_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='verbose_name',
            new_name='verbose_name',
        ),
    ]
