# Generated by Django 2.0.2 on 2018-02-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0022_auto_20171231_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='definition',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
