# Generated by Django 2.0.2 on 2018-02-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0025_auto_20180227_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('definition', models.TextField(blank=True, max_length=250)),
                ('owner_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicationManager.Application')),
            ],
        ),
        migrations.RemoveField(
            model_name='model',
            name='app',
        ),
        migrations.RemoveField(
            model_name='field',
            name='model',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AddField(
            model_name='field',
            name='owner_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='applicationManager.AppModel'),
            preserve_default=False,
        ),
    ]
