# Generated by Django 2.0.2 on 2018-03-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0026_auto_20180228_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='definition',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='owner_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='applicationManager.Application'),
        ),
    ]
