# Generated by Django 2.0.2 on 2018-03-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationManager', '0027_auto_20180302_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='type',
            new_name='field_type',
        ),
    ]
